### ISSUE TITLE
Recording deployments in New Relic

### ISSUE THREAD

**Issue by mwenger1** [thoughtbot/parity#126]
New Relic [supports recording deployments](https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/recording-deployments). I was curious if it was within the scope of parity to support having:

`production deploy` 

send a record event to New Relic

**Comment by geoffharcourt** [comment]
I've been doing this with my client projects that use New Relic, but since it's not assumed that would be in place, I don't think we can do this (I'd rather not build in a bunch of NR-detection code). I think it might be better for projects to do this by a Rake task that gets called by the Heroku buildpack on deploy.

Thoughts?

**Comment by mwenger1** [comment]
Makes sense to find a different approach.

I'm gonna give this [buildpack](https://elements.heroku.com/buildpacks/outlearn/heroku-buildpack-newrelic-deploy) a try.

**Comment by geoffharcourt** [comment]
@mwenger1 I think you can specify custom rake tasks in the main Rails buildpack.
