### ISSUE TITLE
Review App prefix truncated to 22 characters 

### ISSUE THREAD

**Issue by clowder** [thoughtbot/parity#164]
When using the `pr_app` command I was running into issues because we have a long application name, but Heroku appears to truncate that to 22 characters when using it for the Review App prefix.

Opening this as an issue as I've only got a data-point of one and it would be nice to confirm this with other users.

Thanks for all your hard work ❤️ 💻

**Comment by rubendinho** [comment]
Hi @geoffharcourt and @clowder I am experiencing this problem on v3.1

The original app is called: 
`budgit-envelopes-api-staging`
The review app Heroku created:
`budgit-envelopes-api-sta-pr-25`

When i run `pr_app 25 console`, I get:
```
Running bundle exec rails console on ⬢ budgit-envelopes-api-s-pr-25... !
 ▸    Couldn't find that app.
```
So it looks like while Parity is truncating the name to 22 characters as per #165, in my case, Heroku is truncating to 24 characters. 

I suspect that @clowder experienced this issue with a 4-digit PR number (vs my 2-digit one), since Heroku imposes a 30-character limit on app names.  So the solution is probably to truncate up to 30 characters including the `-pr-#{review_app_number}`, rather than chop off the first 22 characters.

![image](https://user-images.githubusercontent.com/12505660/53587637-823d7900-3b50-11e9-8005-be821a734d03.png)
