### ISSUE TITLE
Restore does not pull the latest backup

### ISSUE THREAD

**Issue by alexauritt** [thoughtbot/parity#39]
When I run `development restore production` we seem to be importing a backup that is several weeks old. I've confirmed the existence of and successfully imported more recent backups using the heroku commands directly.

**Comment by geoffharcourt** [comment]
@alexauritt, are you saving your backups with the old or the new Heroku Postgres? Backups saved using the old syntax (`heroku pgbackups:capture`) and the new syntax (`heroku pg:backups capture`) are actually saved to different places (they use different infrastructure), and so won't be restored by the other system's commands.

If you save a new backup using `production backup` and then immediately pull it down with `development restore production`, do you get the correct backup?

**Comment by geoffharcourt** [comment]
The two systems have existed in parallel for many weeks now, in order to allow users to migrate smoothly. Heroku has started to retire the old system, notifying users on an app-by-app basis.

**Comment by alexauritt** [comment]
@geoffharcourt aha I'm sure that's it. Thanks for the heads up. Will investigate.

**Comment by geoffharcourt** [comment]
@alexauritt, in preparation for Heroku shutting down the legacy system, Parity 0.7.0 moved to the new PG system.

**Comment by gohanlon** [comment]
A teammate and I have both experienced this problem when doing successive runs of `development restore production`.

We noticed this when we were heavily testing locally and restoring from production frequently. For us, this wasn't related to capturing backups to the wrong repository.

My guess: Either the Heroku API *sometimes* returns items in an unexpected order, or *sometimes* Parity uses the old repository and sometimes uses the new repository.

(This could have been fixed upstream already — we noticed the problem about 2 weeks ago and haven't used Parity much since.)

**Comment by geoffharcourt** [comment]
Hi @gohanlon, a small question that might help tracking down what's going on: were you waiting for the prior backup to finish? The new backup system continues to run if you aren't watching it over SSH, so you could potentially pull backups before your newest one is finished.

If you can reproduce this, I'd be interested in trying to figure out what's going on.

**Comment by gohanlon** [comment]
@geoffharcourt No explicitly run backup tasks were running. We ran `development restore production` about 20 times in about 30 minutes while debugging a migration. Most of the restore commands gave the expected database, but about every third restore used a stale snapshot.

I'll definitely report back if we see this again. I'm not sure it'll be easy to reproduce. (And, may not be worth the work to try given that it could already be fixed upstream.)
