### ISSUE TITLE
staging restore development

### ISSUE THREAD

**Issue by croaky** [thoughtbot/parity#46]
In order to push a development backup to the staging environment (e.g. `staging restore development`), we'd need to:

* `if from == 'development'` somewhere in [lib/parity/backup.rb](https://github.com/thoughtbot/parity/blob/master/lib/parity/backup.rb)
* `pg_dump -Fc --no-acl --no-owner -h localhost -U myuser mydb > mydb.dump`
* [upload somewhere URL-accessible](https://devcenter.heroku.com/articles/heroku-postgres-import-export#import-to-heroku-postgres)

**Comment by croaky** [comment]
https://devcenter.heroku.com/articles/heroku-postgresql#pg-push works just as well. Should Parity use it?

**Comment by geoffharcourt** [comment]
I have a personal app where this would be really useful. Let me spend a week using `pg-push` to evaluate.

**Comment by geoffharcourt** [comment]
`pg:push` is great, I think we should go ahead and use it. I'm happy to write this PR if you haven't already done a spike of your own.

**Comment by geoffharcourt** [comment]
One more note: in order to do the push, two things need to happen:
1) the user has to wipe the database with `pg:reset`
2) the user needs to confirm, either by typing the app name or appending the `--confirm appname` argument. 

In light of removing configuration in https://github.com/thoughtbot/parity/pull/44, I think we should reconsider always giving the confirmation for staging database restores or pushes.

**Comment by croaky** [comment]
Think we've covered all these ideas now.
